# Obter pelo id de usuário
GET http://localhost:3000/usuario/63604521c2b547e5455f0f74
Content-Type: application/json
###

# Obter usuários filtrando
GET http://localhost:3000/usuario/filtro/gustavo
Content-Type: application/json
###