# Atualizar usuário
PUT http://localhost:3000/usuario-srv
Content-Type: application/json

{
 "_id": "6360457fc424ba5ac80bd871",
    "nome": "Gustavo", 
    "email": "188765@upf.br",
    "celular": "99999-9999", 
    "senha": "123", 
    "dataHoraCad": "2021-01-25T17:32:25.000Z"
}