# Obter pelo id de usuário
GET http://localhost:3000/usuario-srv/63682751a9b613a8ac1253f7
Content-Type: application/json
###

# Obter usuários filtrando
GET http://localhost:3000/usuario-srv/filtro/gustavo
Content-Type: application/json
###